name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test_local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prebuild Docker dpkg container
        run: ./docker-build-dpkg-container
      - name: Download test packages
        run: ./test-download-debs
      - name: Generate test GPG keys
        run: ./test-generate-gpg
      - name: Run tests
        run: ./docker-test-all
  test_as_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download test packages
        run: ./test-download-debs
      - name: Generate test GPG keys
        run: ./test-generate-gpg
      - name: Clean Az Storage container
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch \
              --account-name packageskaitai \
              --source test3 \
              --pattern "*" \
              --sas-token ${{ secrets.TEST_AZURE_STORAGE_SAS_TOKEN }}
      - name: Run action - create repo from scratch
        uses: ./ # Uses an action in the root directory
        id: az_repo_apt_add
        with:
          az_storage_sas_token: ${{ secrets.TEST_AZURE_STORAGE_SAS_TOKEN }}
          az_storage_account: packageskaitai
          az_storage_container: test3
          packages: all_pkgs/kaitai-struct-compiler_0.7_all.deb
      - name: Test install 0.7
        run: |
          mkdir -p test
          ./test-pkg-install-az | tee test/test-0.7.log
          if grep -q 'kaitai-struct-compiler 0.7' test/test-0.7.log; then
            echo OK
          else
            echo FAIL
            exit 1
          fi
